#!/bin/bash
#SBATCH -n 4                # Number of cores
#SBATCH -t 0-10:00          # Runtime in D-HH:MM, minimum of 10 minutes
#SBATCH -p cpu	            # Partition to submit to
#SBATCH --mem=64000           # Memory pool for all cores (see also --mem-per-cpu)

module load gcc/10.4.0 star/2.7.6a
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /scratch/rpurkant/3C_Probe_Design/Genome_Indexes/ABH_genome_index --genomeFastaFiles /scratch/rpurkant/3C_Probe_Design/Genome_Indexes/ABH_genome_index/fDreABH1_chr1-chr25.fa
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir  /scratch/rpurkant/3C_Probe_Design/Genome_Indexes/GRCz11_Yang_chr4_genome_index --genomeFastaFiles /scratch/rpurkant/3C_Probe_Design/Genome_Indexes/GRCz11_Yang_chr4_genome_index/danRer11_chr4-Yang_chr1-chr25.fa
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /scratch/rpurkant/3C_Probe_Design/Genome_Indexes/GRCz11_genome_index --genomeFastaFiles /scratch/rpurkant/3C_Probe_Design/Genome_Indexes/GRCz11_genome_index/danRer11_chr1-chr25.fa
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir /scratch/rpurkant/3C_Probe_Design/Genome_Indexes/TuH_genome_index --genomeFastaFiles /scratch/rpurkant/3C_Probe_Design/Genome_Indexes/TuH_genome_index/fDreTuH1_chr1-chr25.fa
